import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "intro",
    {
      type: "category",
      label: "Getting Started",
      link: { type: "generated-index", title: "Getting Started" },
      items: [{ type: "autogenerated", dirName: "getting-started" }],
    },
    {
      type: "category",
      label: "Editor",
      link: { type: "generated-index", title: "Editor Packages" },
      items: [{ type: "autogenerated", dirName: "editor" }],
    },
    {
      type: "category",
      label: "Guides",
      link: { type: "generated-index", title: "Guides" },
      items: [{ type: "autogenerated", dirName: "guide" }],
    },
    {
      type: "category",
      label: "UI React",
      link: { type: "generated-index", title: "UI React" },
      items: [{ type: "autogenerated", dirName: "ui-react" }],
    },
    {
      type: "category",
      label: "UI Core",
      link: { type: "generated-index", title: "UI Core" },
      items: [{ type: "autogenerated", dirName: "ui-core" }],
    },
    {
      type: "category",
      label: "React Icons",
      link: { type: "generated-index", title: "React Icons" },
      items: [{ type: "autogenerated", dirName: "react-icons" }],
    },
    {
      type: "category",
      label: "Icons",
      link: { type: "generated-index", title: "Icons" },
      items: [{ type: "autogenerated", dirName: "icons" }],
    },
    {
      type: "category",
      label: "Toast",
      link: { type: "generated-index", title: "Toast" },
      items: [{ type: "autogenerated", dirName: "toast" }],
    },
    {
      type: "category",
      label: "Theming",
      link: { type: "generated-index", title: "Theming" },
      items: [{ type: "autogenerated", dirName: "theming" }],
    },
    {
      type: "category",
      label: "Advanced",
      link: { type: "generated-index", title: "Advanced" },
      items: [{ type: "autogenerated", dirName: "advanced" }],
    },
    {
      type: "category",
      label: "Examples",
      link: { type: "generated-index", title: "Examples" },
      items: [{ type: "autogenerated", dirName: "examples" }],
    },
    {
      type: "category",
      label: "Plugin Deep Dives",
      link: { type: "generated-index", title: "Plugin Deep Dives" },
      items: [{ type: "autogenerated", dirName: "plugins" }],
    },
    {
      type: "category",
      label: "Package Deep Dives",
      link: { type: "generated-index", title: "Package Deep Dives" },
      items: [{ type: "autogenerated", dirName: "packages" }],
    },
    {
      type: "category",
      label: "Migration",
      link: { type: "generated-index", title: "Migration" },
      items: [{ type: "autogenerated", dirName: "migration" }],
    },
    {
      type: "category",
      label: "Contributing",
      link: { type: "generated-index", title: "Contributing" },
      items: [{ type: "autogenerated", dirName: "contributing" }],
    },
    {
      type: "category",
      label: "Reference",
      link: { type: "generated-index", title: "Reference" },
      items: [{ type: "autogenerated", dirName: "reference" }],
    },
  ],
};

export default sidebars;
